<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerHp8iycd\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerHp8iycd/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerHp8iycd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHp8iycd\appDevDebugProjectContainer();
